{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: agent-forge
type: Opaque
stringData:
  openai-api-key: {{ .Values.secrets.openaiApiKey | default "" | quote }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-credentials
  namespace: agent-forge
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": {{ .Values.global.dockerHub.username | quote }},
          "password": {{ .Values.global.dockerHub.token | default "" | quote }}
        }
      }
    }
