apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-tool
  namespace: tools
  labels:
    app: example-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-tool
  template:
    metadata:
      labels:
        app: example-tool
    spec:
      containers:
      - name: example-tool
        image: kaw393939/agent-forge-example-tool:latest
        ports:
        - containerPort: 8000
        env:
        - name: REGISTRY_URL
          value: "http://service-registry.registry.svc.cluster.local:8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: example-tool
  namespace: tools
spec:
  selector:
    app: example-tool
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-tool-ingress
  namespace: tools
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - tools.mywebclass.org
    secretName: tools-tls
  rules:
  - host: tools.mywebclass.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-tool
            port:
              number: 8000
