apiVersion: v2
name: agent-forge
description: Agent Forge - A framework for building LLM agents with service mesh capabilities
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - llm
  - agents
  - kubernetes
  - linkerd
home: https://github.com/kaw393939/agent-forge
maintainers:
  - name: Agent Forge Team
    email: admin@mywebclass.org
dependencies:
  - name: cert-manager
    version: "1.12.3"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
  - name: ingress-nginx
    version: "4.7.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
