# Global settings
global:
  domain: mywebclass.org
  environment: dev
  dockerHub:
    username: kaw393939
    repository: agent-forge
    # token will be provided through secrets

# External services configuration
cert-manager:
  enabled: true
  installCRDs: false  # We already installed CRDs separately
  clusterIssuer:
    name: letsencrypt-prod
    kind: ClusterIssuer

ingress-nginx:
  enabled: false  # Disable since it's already installed in the cluster
  controller:
    publishService:
      enabled: true

# Linkerd configuration
linkerd:
  installCLI: true
  dashboardIngress:
    enabled: true
    host: linkerd.mywebclass.org
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: true
      secretName: linkerd-tls

# Registry service configuration
registry:
  enabled: true
  replicas: 1
  image:
    repository: kaw393939/agent-forge-service-registry
    tag: latest
    pullPolicy: Always
  service:
    port: 8000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  ingress:
    enabled: true
    host: registry.mywebclass.org
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: true
      secretName: registry-tls

# Example agent configuration
exampleAgent:
  enabled: true
  replicas: 1
  image:
    repository: kaw393939/agent-forge-example-agent
    tag: latest
    pullPolicy: Always
  service:
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ingress:
    enabled: true
    host: agent.mywebclass.org
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: true
      secretName: agent-tls

# Example tool configuration
exampleTool:
  enabled: true
  replicas: 1
  image:
    repository: kaw393939/agent-forge-example-tool
    tag: latest
    pullPolicy: Always
  service:
    port: 8000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "300m"
  ingress:
    enabled: true
    host: tools.mywebclass.org
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: true
      secretName: tools-tls

# Main website configuration
website:
  enabled: true
  replicas: 1
  image:
    repository: nginx
    tag: stable
    pullPolicy: Always
  service:
    port: 80
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  ingress:
    enabled: true
    hosts:
      - mywebclass.org
      - www.mywebclass.org
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: true
      secretName: website-tls
      hosts:
        - mywebclass.org
        - www.mywebclass.org
  content:
    title: "MyWebClass.org"
    subtitle: "Innovative Learning Solutions"
    description: "Welcome to MyWebClass.org, a platform for modern web development education."

# Streamlit frontend configuration
streamlit:
  enabled: true
  replicas: 1
  image:
    repository: kaw393939/agent-forge-streamlit
    tag: latest
    pullPolicy: Always
  service:
    port: 8501
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ingress:
    enabled: true
    hosts:
      - chat.mywebclass.org
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    tls:
      enabled: true
      secretName: streamlit-tls
      hosts:
        - chat.mywebclass.org
