apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: agents
type: Opaque
stringData:
  openai-api-key: "${OPENAI_API_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "${DOCKER_HUB_USERNAME}",
          "password": "${DOCKER_HUB_TOKEN}"
        }
      }
    }
